{% set name = "jupyterview" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0e887e129838fba3fcdfd81f19f9fe2c8c56c2f51900617467973fe76f7115c4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-nodejs-version
    - hatch-jupyter-builder >=0.5
    - pip
  run:
    - meshio >=5
    - python >=3.8
    - jupyter_server >=2.0.1,<3

test:
  imports:
    - jupyterview

about:
  home: https://github.com/trungleduc/jupyterview
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A VTK Data visualization extension for JupyterLab
  doc_url: https://trungleduc.github.io/jupyterview
  dev_url: https://github.com/trungleduc/jupyterview

extra:
  recipe-maintainers:
    - trungleduc
