{% set name = "jupyterview" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 35286ca71ff8a0b189311a8f6849190e7d9e3ac92ac69ce25cadfe4b8a277d2b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - jupyter-packaging >=0.12
  run:
    - python >=3.6
    - meshio >=5

test:
  imports:
    - jupyterview

about:
  home: https://github.com/trungleduc/jupyterview
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A VTK Data visualization extension for JupyterLab
  doc_url: https://trungleduc.github.io/jupyterview
  dev_url: https://github.com/trungleduc/jupyterview

extra:
  recipe-maintainers:
    - trungleduc
